### ISSUE TITLE
Add 'handy tools/link' sections

### ISSUE THREAD

**Issue by rutgerg** [CalConnect/DEVGUIDE#12]
- http://severinghaus.org/projects/icv/ for testing ics files
- caldav tester
- https://www.calconnect.org/resources/testing-tools-and-links/testing-resources (has some broken and outdated tools)

**Comment by wsdwl** [comment]
Was discussed at last conference and should be done.

**Comment by wsdwl** [comment]
Also add links to documents of providers about the calendaring topic.

**Comment by wsdwl** [comment]
page created -> http://devguide.calconnect.org/Validation

**Comment by wsdwl** [comment]
Done
