### ISSUE TITLE
SSL devguide subdomain

### ISSUE THREAD

**Issue by rutgerg** [CalConnect/DEVGUIDE#13]
The devguide subdomain is not in our certificate at the moment hence users get a warning when using https. Do we want to add this (or any) subdomain to our cert?

**Comment by dthewlis** [comment]
I don’t think we can do anything about it until we have control of our DNS, can we?

**Comment by dmfs** [comment]
You should not need control over  DNS to add sub-domains to the certificate. However, we should bear in mind that we're planning to change this to a CNAME that points to an externally hosted domain (OpenShift or GitHub pages). Once we do that we need to provide the external service with the private key of the certificate to that domain, but we certainly don't want to upload the certificate for www.calconnect.org to any 3rd party service.
So that implies that we need a separate certificate for this subdomain.

**Comment by dthewlis** [comment]
I was thinking of the CNAME plan in fact but thanks for the clarification.

**Comment by wsdwl** [comment]
Still looks that this is not going to be easy as we found https://developers.openshift.com/managing-your-applications/domains-ssl.html, but showing "ustom SSL certificates are not allowed for this application. "

**Comment by gshutler** [comment]
Perhaps stick it behind something like CloudFlare? Their free offering https://www.cloudflare.com/ssl/ should be sufficient and they do the certificate themselves.

**Comment by wsdwl** [comment]
I will check that. Thanks for the tipp.

**Comment by wsdwl** [comment]
I did check, that the process for premium plans work for the working copy of DEVGUIDE, which is now also available via. https://devguide.wsdwl.de/Home. This come with a premium plan at openshift.com and you need a certificate authority, that provide your certificate. In my case I tried startssl.com (whch is no option for others as it will not be accepted by browser in the long run).

I did not check cloudfare.com yet, but have that on my backlog.

**Comment by wsdwl** [comment]
Cloudflare can only be used using a root domain and we don't want to use it for calconnect.org. Therefore Cloudflare is dismissed from the list of possible solutions 👎 

During this, I also created a second development version, so the content can now also be reached using http://devguide2.wsdwl.de/Home 

Next DEVGUIDE call, we need to decide if we are going into the openshift direction or not as this will need to switch to a premium account, where we do not know the cost as it's per calculated usage, which is triggered by the users. The more attractive it gets, the higher the costs for CalConnect for offering.

**Comment by wsdwl** [comment]
I downgraded my account at openshift today and after deleting the certificate it was possible to downgrade. This proofs, that there is a way back, but I would not prefer to go the way with openshift as it includes the risk of unpredictable costs - even if they should not be to high.

**Comment by wsdwl** [comment]
With the switch to the new way of hosting, devguide now is also available via https://devguide.calconnect.org/
