### ISSUE TITLE
Not seeing "Invitees" when trying to add a new calendar item to a caldav calendar

### ISSUE THREAD

**Issue by brianb45401** [CalConnect/DEVGUIDE#16]
Using and iPhone 4 software version iOS 7.1.2 (most up-to-date) for this version of the iPhone.
Have imap mail set-up and it works fine.
Have the calendar (caldav) set-up and it works fine.  I see calendar items from the server and am able to synch across.
Have contacts (cardav) set-up and it works fine.  I see contacts from the server.

However, when I'm in the calendar app and add a new event, there is no invitee option.  I cannot send it to others.  Can anyone help?  Thanks.

**Comment by fatkudu** [comment]
What server are you connecting to and what version of the server?

**Comment by brianb45401** [comment]
Does any of this information help?

cPanel Version 60.0 (build 35)
Apache Version 2.4.23
PHP Version 5.6.26
MySQL Version 5.6.34
Architecture x86_64
Operating System linux
Perl Version 5.8.8
Kernel Version 2.6.32-642.6.199.2.cpanel6.x86_64

**Comment by brianb45401** [comment]
I should also add that when on a Windows desktop using the eM Mail client, it all works correctly.  Meaning, if I create a new calendar item, I have the invitee option and it pulls the names from the common address book.

**Comment by fatkudu** [comment]
I still can't work out what your CalDAV server is.  Perhaps if you explain how you configured your client, that would help identify it.  Note that basic CalDAV does not support scheduling.  The server needs to support https://tools.ietf.org/html/rfc6638 the "calendar-auto-schedule" feature of CalDAV in order for modern Apple clients to work.
It is possible that em Mail client also supports draft-desruisseaux-caldav-sched-03 which was a draft standard on the way to RFC6638 but is radically different (with the draft, the client is responsible for most of the scheduling decisions, with the RFC, the server makes most of the decisions and actually does the scheduling).  The draft was actually supported by Apple clients as well until it was dropped a year or so ago.

**Comment by brianb45401** [comment]
This is the hosting company's response:

We would like to inform you that, CalDAVTester is a test and performance application designed to work with CalDAV and / or CardDAV servers and tests various aspects of their protocol handling as well as performance. its 3rd party application, we suggest you to please contact at CalDAV support end and get the requested details, so we can assist you further.

Would you know what/how to tell then to verify the settings to determine is the server has "auto calendar" feature?

Thank you

**Comment by evert** [comment]
I might be mistaken, but I believe that cPanel out of the box uses Horde to provide CalDAV. Horde (as far as I know) uses an old version of sabre/dav and does _not_ support scheduling.

**Comment by brianb45401** [comment]
Thanks.  We found a workaround.  In the end, they really only need one shared calendar among all of them.  So I just connected everyone to the same calendar and that seems to provide them what they need.  Thank you for your help and suggestions.
