### ISSUE TITLE
discovery of service

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#17]
Create an entry about dicovery of the service

**Comment by wsdwl** [comment]
first thoughts:

- looks good
- add domain in line 22 to clear which domain needs to be asked for well-known URI
- would be nice to add UML diagram

**Comment by wsdwl** [comment]
Keep Bootstrapping and expecially examples separated for CalDav and CardDav (possible references included)

**Comment by wsdwl** [comment]
pushed current version to pre-live and live.

**Comment by douglm** [comment]
Need to extend bootstrap pages to include a step by step guide.

**Comment by wsdwl** [comment]
Ask Sabre.io if we can use their content on 

http://sabre.io/dav/building-a-caldav-client/
http://sabre.io/dav/building-a-carddav-client/

**Comment by wsdwl** [comment]
included in link section.

**Comment by wsdwl** [comment]
copy content from http://sabre.io/dav/service-discovery/ to bootstrapping and rename to discovery of service.

**Comment by wsdwl** [comment]
Done.
