### ISSUE TITLE
Handling time zones right

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#18]
How to save proper time zone information, handling time zones and change of them over time.

Including how to deal with DST?

**Comment by wsdwl** [comment]
Partialy covert in the Best Practice section. Some more work to add regarding timezone changes.

**Comment by douglm** [comment]
Isn't that covered by "What should we be storing"

**Comment by douglm** [comment]
Will change page to add introductory paragraph(s) on timezone rule changes.

**Comment by wsdwl** [comment]
I think, the current state is fine
