### ISSUE TITLE
conversion guide from VCARD 3->4

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#20]
just some more extensions?
More deeper changes?

**Comment by ronaldtse** [comment]
Thanks @wsdwl for putting this up. TC VCARD will be working on this.

**Comment by ronaldtse** [comment]
First draft up, anyone interested in reviewing?

Pinging @wsdwl @dthewlis @douglm @cyrusdaboo @PeterTKY @arnaudq

**Comment by wsdwl** [comment]
Looks good to me and can be viewed on http://devguide.wsdwl.de/vCard/vcard-4.

See comment on #19

**Comment by ronaldtse** [comment]
Thanks @wsdwl , will tackle the data model stuff next time. Should we close this for now?

**Comment by wsdwl** [comment]
It's fine, so we just push this to the live environment.
