### ISSUE TITLE
Review Dates and Times vs Timezones

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#24]
There are two chapters for time related information in the TOC:

3. Handling Dates and Times
5. Timezones

Think about how to combine those two to make it easier for reader to find the relevant information.

Also adding a reference to http://www.isi.edu/touch/pubs/draft-touch-time-00.txt as discussed in https://lists.w3.org/Archives/Public/ietf-http-wg/2017JanMar/thread.html#msg497?

**Comment by wsdwl** [comment]
First part solved by adding reference from 3 to 5.

**Comment by wsdwl** [comment]
Check references within Times and Dates to Figures not included in the version. Where did the original content came from?

**Comment by douglm** [comment]
Actual page is Time-Zones.md
Needs some work

**Comment by wsdwl** [comment]
fine for now
