### ISSUE TITLE
How about adding scheduling 'fun' facts?

### ISSUE THREAD

**Issue by rutgerg** [CalConnect/DEVGUIDE#25]
http://yourcalendricalfallacyis.com/

**Comment by wsdwl** [comment]
Sure and more of them:

http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time
http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time
https://twitter.com/stephenbinns/status/842330300000665601

**Comment by wsdwl** [comment]
created page and added the URLs -> http://devguide.calconnect.org/Appendix/Links

**Comment by wsdwl** [comment]
Done for now. Waiting for more :-)
