### ISSUE TITLE
How to get feedback from users?

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#29]
Idea from today was, adding a feedback option at the bottom of each page of DEVGUIDE to get input from users, if the information provided was reasonable or not.

Identifiy Tools/Forms/Features needed and Obligations coming with that idea.

**Comment by wsdwl** [comment]
Might be an option to use Google forms or a free survey service e.g. survey monkey.

Let's look at Google first (integration in existing Google Drive).

Know someone being able to help formulating the questions?

Start with Yes/No and a chance to describe the reasons for No.

Info on introduction page to lead people missing content, provide that information to us via feedback.

**Comment by wsdwl** [comment]
done
- [ ] create Google form within CalConnect Google Drive
- [ ] Integration in Prelive stage with basic styling
- [ ] make test entry

next
- [ ] review wording (native speaker)
- [ ] decide if ready for first launch 
- [ ] launch

**Comment by wsdwl** [comment]
Checked with @dthewlis and @douglm and pushed it lo live.

Also managed to receive notifications about responses, so wait and see :-)

**Comment by wsdwl** [comment]
Reopened to review and wait for responses.

**Comment by gshutler** [comment]
Wording suggestion:

> **CalConnect Developer's Guide Feedback**
>
> Your feedback helps us make the guide more useful!
>
> **Did you find what you were looking for?** *
> Yes / No
> 
> **What topics are missing or would you like to be covered in more depth?**
> Your answer
>
> **Your email address (optional, we may contact you for further feedback)**
> Your answer

**Comment by wsdwl** [comment]
Thanks @gshutler ! I just edited the wording.

**Comment by wsdwl** [comment]
Status: no response received until today.

**Comment by wsdwl** [comment]
Current Status:
- 2 spam responses
- 2 responses telling, the found what they were searching for with no email address provided

Therefor I would assume, that the issues can be closed, beaing able to get the feedback. This is also proved for the new website, we are switching within the next days.
