### ISSUE TITLE
Reader comment #1

### ISSUE THREAD

**Issue by dmfs** [CalConnect/DEVGUIDE#3]
I miss an introduction and guidance for the reader. Is there an idea of who should read it, why and with what idea should the reader leave this guide? Looking at https://devguide-calconnect.rhcloud.com/Table-of-Contents a lot of content is missing.

**Comment by cyrusdaboo** [comment]
Has been addressed by updates to the ToC page and the Introduction page.

**Comment by dmfs** [comment]
@rutgerg please review the latest changes and comment

**Comment by cyrusdaboo** [comment]
We believe this has been addressed now. Please create a new issue with specific changes you would like to see if you are still unhappy with the introduction.
