### ISSUE TITLE
Find a new way of hosting the DEVGUIDE

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#31]
As openshift v2 is shutting down by the end of September 2017, we need to find a new solution to host our pages.

This offers the chance to provide [SSL](https://github.com/CalConnect/DEVGUIDE/issues/13) also.

**Comment by dmfs** [comment]
In the meantime I've launched a blog with [Jinja](http://jinja.pocoo.org/docs/2.9/), which seems to be a good alternative to Gollum. In particular it has many plugins for pagers and other nice stuff.
Also it uses Markdown by default, so only few changes are required.
There are a number of themes for Jinja.
GitHb pages also supports Jinja but doesn't support custom plugins. Also GitHub pages doesn't support SSL for custom domains.

Anyway, using Jinja you can create the static HTML files locally and serve them as static files with any hosting service. So all you need is a host for static web sites.

**Comment by dmfs** [comment]
Sorry, when I wrote "Jinja" I actually means [Jekyll](https://jekyllrb.com/). I sometimes confuse these two names :-|

**Comment by wsdwl** [comment]
I did start playing around with Jekyll and made a static version (not layouted yet) of DEVGUIDE being available at http://devguide-static.wsdwl.de/ and all files at https://github.com/wsdwl/DEVGUIDE-static for further discussion at our call tomorrow.

**Comment by wsdwl** [comment]
Next steps:
- try to use the existing mustache layout files -> @dmfs 
- look for hosting options at Google Apps -> @dmfs 
- describe what needed when hosting at SCG -> @wsdwl
- look for possible plugins (search/plantuml/...) -> @wsdwl

**Comment by wsdwl** [comment]
Doing fine with the transition. Need to look into search at the developers forum in Cologne. https://community.algolia.com/docsearch/  might be an option or local JSON file.

**Comment by wsdwl** [comment]
Switch to Google App Engine has been initiated and CNAME change is waiting for the cache to be expired.

**Comment by wsdwl** [comment]
DNS switch was done successfully.

Maybe we need to add a redirect for /Home for people who used it before.

**Comment by wsdwl** [comment]
Switched the repository to now contain the up-to-date, but reformated version of the content for jekyll build and Google App engine deployment.

**Comment by wsdwl** [comment]
last changes:
- adding redirect for /Home
- fixing relative links, when redirecting from [caldav|carddav].calconnect.org

open:
- create solution for search -> TC work, suggestions above
- fix redirecting with URI from [caldav|carddav].calconnect.org -> addressed to Arlen

**Comment by wsdwl** [comment]
Thats how the pages might look in the future:

![a-history-of-icalendar](https://user-images.githubusercontent.com/9115626/31503388-cc35ab36-af6f-11e7-92f5-df18c92a7550.png)

**Comment by dmfs** [comment]
nice!

**Comment by wsdwl** [comment]
also still needed: short documentation about how to create the environment locally.

**Comment by wsdwl** [comment]
Styling updated. It now looks really good with improved browsing links!

**Comment by wsdwl** [comment]
UX improvement finished and put online two weeks ago.

As we now have everything in place, I will close this ticket.

**Comment by wsdwl** [comment]
I was to fast. Still open: 

- create solution for search -> TC work, suggestions above
- fix redirecting with URI from [caldav\|carddav].calconnect.org -> addressed to Arlen (again today)
- short documentation about how to create the environment locally and push content to live

**Comment by wsdwl** [comment]
Changes since last time:
* short documentation done in Googlepad
* Test of an alternative hosting option using Google firebase: https://calconnect-devguide-trial.firebaseapp.com
* added 404 handling to firebase

Next:
* test firebase
* add rewrites for known error URLs from old server
* move domain at next conference together with @dmfs

**Comment by wsdwl** [comment]
Moved to firebase, works fine. Redirect created.
Therefor I would close the subject.
