### ISSUE TITLE
Glossary points to RSCALE Draft

### ISSUE THREAD

**Issue by dmfs** [CalConnect/DEVGUIDE#39]
The spec has been promoted to a standard in 2015 as RFC 7529: https://tools.ietf.org/html/rfc7529

**Comment by wsdwl** [comment]
Overall clean up of glossary needed including changing the link on https://www.calconnect.org

**Comment by douglm** [comment]
Add reference to calsify

**Comment by wsdwl** [comment]
done and pushed to the server
