### ISSUE TITLE
Reader comment #2

### ISSUE THREAD

**Issue by dmfs** [CalConnect/DEVGUIDE#4]
Is the idea to put more human readable text to it? https://devguide-calconnect.rhcloud.com/History may be factual correct but is imo unreadable.

**Comment by dmfs** [comment]
@rutgerg What content are you missing in the History page?

**Comment by rutgerg** [comment]
I see an introduction is added to the devguide. I think that is a good idea and gives 'history' its proper place and context. At the time of my earlier remark the first page of de devguide was the history page. Starting with mentioning alle RFCs from the past didn't seem that enticing for aspirational calendar developers.
