### ISSUE TITLE
wrong RECURRENCE-ID in example

### ISSUE THREAD

**Issue by dmfs** [CalConnect/DEVGUIDE#45]
The override in the example at https://devguide.calconnect.org/Data-Model/UID/#handling-uids-inside-recurrent-events has a `RECURRENCE-ID` which is not part of the recurrence set. The original event recurs at 11:00, but the `RECURRENCE-ID` says  `T120000`. 
`DTSTART` and `DTEND` look pretty bogus as well. The original event spans 3 days but recurs every day (which means the instances overlap) and the override doesn't actually change anything.

**Comment by wsdwl** [comment]
Would it be fixed with that pull request? https://github.com/CalConnect/DEVGUIDE/pull/46

**Comment by wsdwl** [comment]
OK. I think, I fixed it in the right way. @dmfs Please have a look.

**Comment by dmfs** [comment]
yep looks good now.
