### ISSUE TITLE
Theme github pages of public

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#55]
Use individual CalConnect theme for https://calconnect.github.io/public/ re-using the layout from DEVGUIDE

Description about how to do this: https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

**Comment by wsdwl** [comment]
Will be part of our next calendar sprint within 1&1, pull request should come soon.

**Comment by wsdwl** [comment]
fixed part of the problem, but not all. There is a missing /public/ in the URL. We will take care of that tomorrow.

**Comment by alessioalex** [comment]
I made another commit which is supposed to fix this problem @wsdwl https://github.com/CalConnect/public/pull/2

**Comment by wsdwl** [comment]
Works now! Thanks @alessioalex !
