### ISSUE TITLE
Styling hides nested nature of email structure

### ISSUE THREAD

**Issue by gshutler** [CalConnect/DEVGUIDE#57]
https://github.com/CalConnect/DEVGUIDE/blob/master/_pages/Scheduling/iMIP.md#best-practices

Looks like this:

![imip](https://user-images.githubusercontent.com/81344/41584278-cc8bded6-739e-11e8-9b43-3bfe18af703d.png)

Seems a global style so not sure how best to change but loses the information of the nesting (after suppressing a couple of styles through the debugger):

![imip](https://user-images.githubusercontent.com/81344/41584308-e2127e2c-739e-11e8-94b9-e5c789f4a7ca.png)

**Comment by wsdwl** [comment]
Will be part of our next calendar sprint within 1&1
