### ISSUE TITLE
fix plantuml issue

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#60]
plant uml is used on some of the pages. After moving to firebase, it does not work anymore

e.g. https://devguide.calconnect.org/Recurrences/

Seems to be a local build problem, but haven't been ablt to fix it yet :-(

**Comment by dmfs** [comment]
We didn't really change anything on how this is built. I'll look into that.

**Comment by wsdwl** [comment]
Looks like being a local problem on my machine. Investigating further.

**Comment by wsdwl** [comment]
fixed.

The plantuml svg where cached (see https://github.com/asciidoctor/asciidoctor-diagram/issues/126). 

Deleting them and building again worked for me and I was able to deploy the working version.
