### ISSUE TITLE
Investigate analytics

### ISSUE THREAD

**Issue by douglm** [CalConnect/DEVGUIDE#8]
Nice to see the traffic to the site

**Comment by wsdwl** [comment]
Make this independen form the overall new website topic.

Next step:
- Create or use an existing account from CalConnect for creating the responding Google Analytics Account
- find out, how the snippet needs to look like, which should be included in the footer section

**Comment by rutgerg** [comment]
Me and Dave will set up a GA account and provide you with the snippet

**Comment by rutgerg** [comment]
Copy/paste this code in header or footer

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-22761082-2', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by douglm** [comment]
All I see is that below - maybe send as an attachment?

**Comment by rutgerg** [comment]
I make md error with initial comment which was sent arounf. If you check comment on github.com now you see snippet

**Comment by wsdwl** [comment]
I did a integration of that snippet in the DEVGUIDE-CONFIG repo and pushed the changes to my copy of DEVGUIDE. It's now integrated there.

@rutgerg: Can you please check, if the few page impressions I made this morning are shown in the Analytics console?

**Comment by rutgerg** [comment]
Yep. About 30 mins ago.

**Comment by wsdwl** [comment]
OK. I did pushed it also the the official CalConnect DEVGUIDE version and you should be able to see the traffic in the future.

**Comment by rutgerg** [comment]
Anybody wants to be added to Ganalytics account to see or receive analytics? If so, send me an email with the email address you want added

**Comment by douglm** [comment]
I'd be interested in seeing the results

**Comment by rutgerg** [comment]
We have data coming in
