### ISSUE TITLE
Update DNS to migrate site to Github Pages

### ISSUE THREAD

**Issue by kwkwan** [CalConnect/DEVGUIDE#80]
Hi @ronaldtse and @douglm, the Github actions are updated to deploy the site to Github Pages.  Please updated DNS CNAME record to point `devguide.calconnect.org` to `calconnect.github.io`.  Thank you.

**Comment by ronaldtse** [comment]
Thank you @kwkwan !

**Comment by douglm** [comment]
Added CNAME record. Had to remove and re-add the custom domain to force a DNS check.

Looks good. Thank you for the work.

**Comment by kwkwan** [comment]
Closed #80 as completed.

**Comment by ronaldtse** [comment]
This works. Perfect. Thanks!
